### ISSUE TITLE
htu21d fatal error

### ISSUE THREAD

**Issue by Zhurzhin** [pedalPusher68/node-red-contrib-brads-i2c-nodes#5]
hi
on pi Zero:

14 Sep 14:06:07 - [info] Node-RED version: v0.17.5
14 Sep 14:06:07 - [info] Node.js  version: v6.11.3
14 Sep 14:06:07 - [info] Linux 4.9.41+ arm LE
14 Sep 14:06:12 - [info] Loading palette nodes
14 Sep 14:06:38 - [info] Dashboard version 2.4.3 started at /ui
14 Sep 14:06:40 - [info] Settings file  : /root/.node-red/settings.js
14 Sep 14:06:40 - [info] User directory : /root/.node-red
14 Sep 14:06:40 - [info] Flows file     : /root/.node-red/flows_raspberrypi.json 

14 Sep 14:08:11 - [red] Uncaught Exception:
14 Sep 14:08:11 - Error: Unknown encoding: 2
  at assertEncoding (fs.js:129:11)
  at Object.fs.read (fs.js:656:5)
  at Object.read (/usr/lib/node_modules/node-red-contrib-npm/node_modules/npm/node_modules/graceful-fs/polyfills.js:103:20)
  at Bus.<anonymous> (/usr/lib/node_modules/i2c-bus/i2c-bus.js:329:8)
  at runCallback (timers.js:676:20)
  at tryOnImmediate (timers.js:645:5)
  at processImmediate [as _immediateCallback] (timers.js:617:5)   

how fix it?

**Comment by Lennyz1988** [comment]
Same here. Using this sensor node makes my Node-red crash.
